# Generated by Django 6.0.4 on 2026-04-20 17:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('pu_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('lga', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('ward', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(choices=[('sms', 'SMS'), ('web', 'Web')], default='sms')),
                ('urgency_score', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('category', models.CharField(choices=[('logistics', 'Logistics (Materials/Staff)'), ('security', 'Security Threat'), ('fraud', 'Malpractice/Fraud'), ('technical', 'BVAS/Technical Issues'), ('other', 'Other')], default='others')),
                ('ai_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polling_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='authentication.pollingunit')),
            ],
            options={
                'ordering': ['-urgency_score', '-created_at'],
            },
        ),
    ]
