# Generated by Django 6.0.4 on 2026-05-20 02:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('triage_agent', 'Triage Agent'), ('cso_admin', 'CSO Admin'), ('superadmin', 'Super Admin')], default='triage_agent', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='admin_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='admin_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Admin User',
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('reporter_name', models.CharField(blank=True, max_length=255)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('raw_location', models.CharField(blank=True, max_length=500)),
                ('urgency_score', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('category', models.CharField(choices=[('logistics', 'Logistics (Materials/Staff)'), ('security', 'Security Threat'), ('fraud', 'Malpractice/Fraud'), ('technical', 'BVAS/Technical Issues'), ('other', 'Other')], default='other', max_length=20)),
                ('ai_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('report_count', models.IntegerField(default=1)),
                ('cluster_id', models.CharField(blank=True, max_length=50)),
                ('incident_type', models.CharField(choices=[('missing_materials', 'Missing Materials'), ('delayed_staff', 'Delayed Staff'), ('security_threat', 'Security Threat'), ('voter_suppression', 'Voter Suppression'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('sms', 'SMS'), ('web', 'Web')], default='sms', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('flagged', 'Flagged'), ('triaged', 'Triaged'), ('verified', 'Verified'), ('closed', 'Closed')], default='pending', max_length=15)),
                ('review_notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='incidents/media/')),
                ('media_url', models.URLField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', models.URLField()),
                ('cloudinary_public_id', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='authentication.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('pu_code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pu_name', models.CharField(max_length=150)),
                ('lga', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('ward', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'polling_units',
                'ordering': ['state', 'lga', 'ward'],
                'indexes': [models.Index(fields=['state', 'lga'], name='polling_uni_state_aa5236_idx'), models.Index(fields=['pu_code'], name='polling_uni_pu_code_7010e7_idx')],
            },
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='polling_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='authentication.pollingunit'),
        ),
        migrations.CreateModel(
            name='TriageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('logistics', 'Logistics'), ('security', 'Security'), ('electoral', 'Electoral Process'), ('other', 'Other')], max_length=20)),
                ('severity', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='authentication.incidentreport')),
            ],
            options={
                'db_table': 'triage_data',
            },
        ),
        migrations.CreateModel(
            name='TriageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_ai_response', models.JSONField()),
                ('prompt_used', models.TextField()),
                ('processing_time_ms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_logs', to='authentication.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='WardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='ward_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='ward_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('observer', 'Observer'), ('agent', 'Ward Agent'), ('officer', 'Electoral Officer')], default='observer', max_length=20)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authentication.warduser')),
            ],
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['status'], name='incident_re_status_919c25_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['incident_type'], name='incident_re_inciden_6bfa21_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['created_at'], name='incident_re_created_c2fe61_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentreport',
            index=models.Index(fields=['is_deleted'], name='incident_re_is_dele_620e1d_idx'),
        ),
    ]
